CREATE TABLE "Users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL DEFAULT '',
  "email" varchar UNIQUE NOT NULL DEFAULT '',
  "password" varchar NOT NULL DEFAULT '',
  "id_rol" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "Roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_rol" varchar NOT NULL DEFAULT ''
);

CREATE TABLE "Servicios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL DEFAULT '',
  "precio" integer NOT NULL DEFAULT 0,
  "puntos_por_servicio" integer NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "Reserva" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer NOT NULL,
  "id_servicio" integer NOT NULL,
  "fecha_hora" timestamptz NOT NULL DEFAULT (now()),
  "estado" varchar NOT NULL DEFAULT 'pendiente',
  "correo_enviado" boolean DEFAULT false,
  "feedback_enviado" boolean DEFAULT false,
  "confirmacion_presencial" boolean DEFAULT false
);

CREATE TABLE "Puntos_Acumulados" (
  "id_usuario" integer PRIMARY KEY,
  "puntos_acumulados" integer NOT NULL DEFAULT 0,
  "last_updated" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "Feedback" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_reserva" integer NOT NULL,
  "valoracion" integer NOT NULL DEFAULT 0,
  "comentarios" text NOT NULL DEFAULT '',
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

ALTER TABLE "Users" ADD FOREIGN KEY ("id_rol") REFERENCES "Roles" ("id");

ALTER TABLE "Reserva" ADD FOREIGN KEY ("id_usuario") REFERENCES "Users" ("id");

ALTER TABLE "Reserva" ADD FOREIGN KEY ("id_servicio") REFERENCES "Servicios" ("id");

ALTER TABLE "Puntos_Acumulados" ADD FOREIGN KEY ("id_usuario") REFERENCES "Users" ("id");

ALTER TABLE "Feedback" ADD FOREIGN KEY ("id_reserva") REFERENCES "Reserva" ("id");

insert into "Roles" ("nombre_rol") 
  values ('admin'),('cliente');

insert into "Users" ("nombre","email","password","id_rol") values 
  ('admin','adm@adm.cl','$2b$10$6CaxPcda7RtARiUtlo1xq.0KU3rdjkeLid2tNiDFWyGPP1WTHQMpO',1),
  ('client','c@c.cl','$2b$10$6CaxPcda7RtARiUtlo1xq.0KU3rdjkeLid2tNiDFWyGPP1WTHQMpO',2),
  ('Fernando','fernando.vax20@gmail.com','$2b$10$6CaxPcda7RtARiUtlo1xq.0KU3rdjkeLid2tNiDFWyGPP1WTHQMpO',2);

insert into "Servicios" ("nombre","precio","puntos_por_servicio") 
  values 
    ('Corte de pelo'                           ,10000,100),
    ('Corte de pelo y perfilado de barba corta',16000,200),
    ('Corte de pelo y perfilado de barba larga',20000,200),
    ('Corte de pelo y afeitado al ras'         ,18000,200);